version: "2.1"

# Balena docker-compose.yml for standing up a k3s server and bastion

services:
  server:
    # https://docs.k3s.io/advanced#running-k3s-in-docker
    build:
      context: deploy/balena-k3s/server
      args:
        # Setting ENABLE_GPU to false avoids installing nvidia drivers, nvidia container runtime, etc.
        ENABLE_GPU: &enable_gpu false
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    network_mode: host
    environment:
      # https://docs.k3s.io/cli/server#cluster-options
      K3S_KUBECONFIG_OUTPUT: "/shared/kubeconfig.yaml"
      K3S_KUBECONFIG_MODE: "644"
      EXTRA_K3S_SERVER_ARGS: "--disable traefik"
      INFERENCE_FLAVOR: "CPU"
      ENABLE_GPU: *enable_gpu
    tmpfs:
      - /run
      - /var/run
    volumes:
      - k3s-server:/var/lib/rancher/k3s
      - shared:/shared

  bastion:
    build:
      context: .
      dockerfile: deploy/balena-k3s/bastion/Dockerfile
    network_mode: host
    environment:
      KUBECONFIG: "/shared/kubeconfig.yaml"
    volumes:
      - shared:/shared:ro
    depends_on:
      - server

volumes:
  k3s-server: {}
  shared: {}