apiVersion: v1
kind: Namespace
metadata:
  name: gpu-operator
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nvidia-gpu-operator
  namespace: kube-system
  annotations:
    helm.cattle.io/helm-controller: "true"
spec:
  repo: https://nvidia.github.io/gpu-operator
  chart: gpu-operator
  targetNamespace: gpu-operator
  wait: true
  bootstrap: true  # Add this to ensure it's processed during bootstrap
  # https://github.com/NVIDIA/gpu-operator/blob/main/deployments/gpu-operator/values.yaml
  valuesContent: |-
    driver:
      enabled: false  # Disable NVIDIA driver installation since we have it pre-installed
    toolkit:
      enabled: false  # Disable NVIDIA Container Toolkit installation since we have it pre-installed
    dcgm:
      enabled: false  # Disable DCGM since we don't care
    dcgmExporter:
      enabled: false  # Disable DCGM exporter since we don't care
