{{- define "edge-endpoint.registry-credentials.podSpec" -}}
restartPolicy: Never
serviceAccountName: edge-endpoint-service-account

containers:
  - name: aws-cli
    image: amazon/aws-cli:latest
    command:
      - /bin/sh
      - /app/init-aws-access.sh
    env:
      - name: GROUNDLIGHT_ENDPOINT
        value: "{{ .Values.groundlightEndpoint }}"
      - name: GROUNDLIGHT_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: groundlight-api-token
            key: GROUNDLIGHT_API_TOKEN

    volumeMounts:
      - name: shared-volume
        mountPath: /shared
      - name: init-aws-access
        mountPath: /app/init-aws-access.sh
        subPath: init-aws-access.sh

  - name: kubectl
    image: bitnami/kubectl:latest
    command:
      - /bin/sh
      - -c
      - |
        sleep 5  # Ensure the token is written before using it
        kubectl create secret -n "{{ .Values.namespace }}" docker-registry registry-credentials \
          --docker-server={{ .Values.ecrRegistry }} \
          --docker-username=AWS \
          --docker-password="$(cat /shared/token.txt)" \
          --dry-run=client -o yaml | kubectl apply -f -

        kubectl create secret generic aws-credentials-file --from-file /shared/credentials
    volumeMounts:
      - name: shared-volume
        mountPath: /shared
volumes:
  - name: init-aws-access
    configMap:
      name: init-aws-access
  - name: shared-volume
    emptyDir: {}
{{- end }}