{{- /* TODO: Replace this with fetching temporary creds from Janzu */ -}}
{{- if or (not .Values.awsAccessKeyId) (not .Values.awsSecretAccessKey) }}
{{ fail "Both awsAccessKeyId and awsSecretAccessKey must be set" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
data: 
  aws_access_key_id: {{ .Values.awsAccessKeyId | b64enc | quote }}
  aws_secret_access_key: {{ .Values.awsSecretAccessKey | b64enc | quote }}
