apiVersion: batch/v1
kind: Job
metadata:
  name: create-ecr-creds
  namespace: "{{ .Values.namespace }}"
spec:
  template:
    spec:
    {{- include "edge-endpoint.registry-credentials.podSpec" . | nindent 6 }}