apiVersion: v1
kind: ConfigMap
metadata:
  name: init-aws-access
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "groundlight-edge-endpoint.labels" . | nindent 4 }}
data:
  init-aws-access.sh: |
    {{- tpl (.Files.Get "files/init-aws-access.sh") . | nindent 4 }}
