{{- if .Values.k3sConfig.enabled }}
# ServiceAccount and RBAC for the k3s memory configuration job.
# This creates a dedicated service account with cluster-admin privileges
# needed for the k3s-memory-config job

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "groundlight-edge-endpoint.serviceAccountName" . }}-k3s-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "groundlight-edge-endpoint.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "groundlight-edge-endpoint.fullname" . }}-k3s-config
  labels:
    {{- include "groundlight-edge-endpoint.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ include "groundlight-edge-endpoint.serviceAccountName" . }}-k3s-config
  namespace: {{ .Values.namespace }}
{{- end }}