apiVersion: v1 
kind: PersistentVolume 
metadata:
  name: {{ .Values.persistentVolumeName }}
spec:
  capacity: 
    storage: 2Gi
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/groundlight/edge
---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: edge-endpoint-pvc
  namespace: {{ .Values.namespace }}
spec: 
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 2Gi