apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "groundlight-edge-endpoint.labels" . | nindent 4 }}
data:
  nginx.conf: |
    {{- tpl (.Files.Get "files/nginx.conf") . | nindent 4 }}
  dummy-nginx.conf: |
    {{- tpl (.Files.Get "files/dummy-nginx.conf") . | nindent 4 }}
