{{- if or (eq .Values.loggingMode "local-splunk") (eq .Values.loggingMode "cloud-splunk") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: {{ .Values.namespace }}
data:
  otel-config.yaml: |
    receivers:
      # Filelog receiver to read container logs from Kubernetes
      filelog:
        include:
          - /var/log/pods/{{ .Values.namespace }}_*/*/*.log
        exclude:
          # Exclude otel-collector's own logs to prevent loops
          - /var/log/pods/{{ .Values.namespace }}_*/*otel-collector*/*.log
        start_at: end
        include_file_path: true
        include_file_name: false
        operators:
          - id: container
            type: container     # populates k8s.pod.uid, k8s.container.name, etc.
          # First extract Kubernetes metadata from file path
          - type: regex_parser
            id: extract_metadata_from_filepath
            regex: '^.*\/(?P<namespace>[^_]+)_(?P<pod_name>[^_]+)_(?P<uid>[a-f0-9\-]{36})\/(?P<container_name>[^\._]+)\/(?P<restart_count>\d+)\.log$'
            parse_from: attributes["log.file.path"]
            output: parse_cri_format
          # Parse CRI format: timestamp stdout/stderr F message
          - type: regex_parser
            id: parse_cri_format
            regex: '^(?P<timestamp>[^\s]+)\s+(?P<stream>stdout|stderr)\s+(?P<partial>F|P)(\s+(?P<message>.*))?$'
            parse_from: body
            # timestamp:
            #   parse_from: attributes.timestamp
            #   layout: '%Y-%m-%dT%H:%M:%S.%f%z'
            #   location: 'Local'
            output: extract_log_level
          # Extract log level from message
          - type: regex_parser
            id: extract_log_level
            # Match log patterns like: "INFO: message" or "2025-09-23 17:42:23.192 INFO message" 
            regex: '^(?:\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2}[.]\d+\s+)?(?P<log_level>TRACE|DEBUG|INFO|WARN|WARNING|ERROR|CRITICAL|FATAL)[:,]?\s*(?P<clean_message>.*)$'
            parse_from: attributes.message
            on_error: 'send'  # Send original message if regex doesn't match

    processors:
      # Add Kubernetes attributes using the Kubernetes API
      k8sattributes:
        auth_type: "serviceAccount"
        passthrough: false
        filter:
          node_from_env_var: KUBE_NODE_NAME
        extract:
          metadata:
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.deployment.name
            - k8s.namespace.name
            - k8s.node.name
            - k8s.pod.start_time
            - k8s.container.name
            - container.image.name
            - container.image.tag
          labels:
            - tag_name: app
              key: app
            - tag_name: version
              key: version
            - tag_name: component
              key: component
            - tag_name: pod-template-hash
              key: pod-template-hash
          annotations:
            - tag_name: deployment
              key: deployment.kubernetes.io/revision

      # Add resource attributes
      resource:
        attributes:
          - key: service.name
            value: "edge-endpoint"
            action: upsert
          - key: service.version
            from_attribute: version
            action: insert
          - key: deployment.environment
            value: "edge"
            action: upsert
          # Use pod name as host identifier (more reliable than node name)
          - key: host.name
            from_attribute: k8s.pod.name
            action: upsert
          # Add Balena device UUID if available
          - key: balena.device.uuid
            value: "${env:BALENA_DEVICE_UUID}"
            action: insert
          # Map extracted log level for searchability
          - key: log.level
            from_attribute: log_level
            action: insert
          # Use cleaned message without timestamp/level prefix  
          - key: log.message
            from_attribute: clean_message
            action: insert
          # Container image info not available via k8sattributes - would need custom solution
          # Add IP address information
          - key: pod.ip
            value: "${env:POD_IP}"
            action: insert
          - key: node.ip
            value: "${env:NODE_IP}"
            action: insert

      # Batch processor for performance
      batch:
        timeout: 1s
        send_batch_size: 1024

    exporters:
      # Splunk HEC exporter
      splunk_hec:
        {{- if eq .Values.loggingMode "local-splunk" }}
        endpoint: "http://splunk:8088/services/collector"
        token: {{ .Values.splunk.local.hecToken | quote }}
        {{- else if eq .Values.loggingMode "cloud-splunk" }}
        endpoint: {{ .Values.splunk.cloud.endpoint | quote }}
        token: {{ .Values.splunk.cloud.token | quote }}
        {{- end }}
        index: {{ .Values.splunk.index | quote }}
        source: {{ .Values.splunk.source | quote }}
        sourcetype: {{ .Values.splunk.sourcetype | quote }}
        disable_compression: false
        timeout: 10s
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 120s

      # Debug exporter for troubleshooting (optional)
      debug:
        verbosity: basic

    service:
      pipelines:
        logs:
          receivers: [filelog]
          processors: [k8sattributes, resource, batch]
          exporters: [splunk_hec]
{{- end }}
