{{- if eq .Values.loggingMode "local-splunk" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: splunk-config
  namespace: {{ .Values.namespace }}
data:
  indexes.conf: |
    # Custom indexes for edge-endpoint
    [edge_app]
    homePath = $SPLUNK_DB/edge_app/db
    coldPath = $SPLUNK_DB/edge_app/colddb
    thawedPath = $SPLUNK_DB/edge_app/thaweddb
    maxDataSize = auto_high_volume
    datatype = event

    [edge_events]
    homePath = $SPLUNK_DB/edge_events/db
    coldPath = $SPLUNK_DB/edge_events/colddb
    thawedPath = $SPLUNK_DB/edge_events/thaweddb
    maxDataSize = auto_high_volume
    datatype = event

    [edge_metrics]
    homePath = $SPLUNK_DB/edge_metrics/db
    coldPath = $SPLUNK_DB/edge_metrics/colddb
    thawedPath = $SPLUNK_DB/edge_metrics/thaweddb
    maxDataSize = auto_high_volume
    datatype = metric

    [edge_errors]
    homePath = $SPLUNK_DB/edge_errors/db
    coldPath = $SPLUNK_DB/edge_errors/colddb
    thawedPath = $SPLUNK_DB/edge_errors/thaweddb
    maxDataSize = auto_high_volume
    datatype = event
{{- end }}
