extends: default

rules:
  document-start: disable
  indentation:
    spaces: consistent
    level: error
  line-length:
    max: 150
    level: warning
  comments: disable
  trailing-spaces: disable
