version: "2.1"

# Balena docker-compose.yml for standing up a k3s server and bastion
# https://github.com/k3s-io/k3s/blob/master/docker-compose.yml

services:
  server:
    # https://docs.k3s.io/advanced#running-k3s-in-docker
    build:
      context: deploy/balena-k3s/server
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    network_mode: host
    # https://docs.k3s.io/cli/server#cluster-options
    environment:
      K3S_KUBECONFIG_OUTPUT: "/shared/kubeconfig.yaml"
      K3S_KUBECONFIG_MODE: "666"
      EXTRA_K3S_SERVER_ARGS: ""
    tmpfs:
      - /run
      - /var/run
    volumes:
      - k3s-server:/var/lib/rancher/k3s
      - shared:/shared

  bastion:
    build:
      context: .
      dockerfile: deploy/balena-k3s/bastion/Dockerfile
    network_mode: host
    environment:
      KUBECONFIG: "/shared/kubeconfig.yaml"
    volumes:
      - shared:/shared:ro
    depends_on:
      - server

volumes:
  k3s-server: {}
  shared: {}