[tool.poetry]
name = "groundlight-edge"
version = "0.1.0"
description = "Run groundlight on the edge!"
authors = ["Groundlight AI <support@groundlight.ai>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.11"
uvicorn = { version = "0.20.0", extras = ["standard"] }
fastapi = "0.88.0"
pydantic = "^1.10.2"

[tool.poetry.dev-dependencies]
pytest = "7.2.0"
pytest-cov = "4.0.0"
coverage = "6.5.0"
black = "22.12.0"
requests = "2.28.1"
pre-commit = "2.20.0"

# https://docs.pytest.org/en/latest/reference/customize.html

[tool.poetry.group.dev.dependencies]
httpx = "^0.23.1"

[tool.pytest.ini_options]
testpaths = ["test"]

# https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-via-a-file
[tool.black]
line-length = 120

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
