[project]
name = "ee-cicd"
version = "0.1.0"
description = "Automated e2e testing of a new Edge Endpoint"
requires-python = ">=3.10"
dependencies = [
    "pulumi>=3.0.0,<4.0.0",
    "pulumi-aws>=6.0.2,<7.0.0",
    "boto3>=1.36.0,<2.0.0",
]
