[project]
name = "pulumi-ee-cicd"
version = "0.1.0"
description = "Pulumi code for Edge Endpoint CI/CD"
requires-python = ">=3.10"
dependencies = [
    "pulumi>=3",
    "pulumi-aws>=6.13.3",
    "boto3>=1.36.1",
    "groundlight>=0.22.6, <0.23.0",
    "fabric>=3.2.2",
]
