apiVersion: batch/v1
kind: Job
metadata:
  name: warmup-inference-model
spec:
  template:
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
      - name: registry-credentials
      containers:
      - name: image-puller
        image: 767397850842.dkr.ecr.us-west-2.amazonaws.com/gl-edge-inference:latest
        command: ["echo", "Successfully pulled image to warm cache"]
      - name: sync-pinamod
        image: amazon/aws-cli:latest
        # Sync models and HF proxy content from S3 to the local hostmapped filesystem.
        command: ['sh', '-c']
        args:
        - |
          echo "Syncing pinamod models..."
          aws s3 sync s3://pinamod-artifacts-public/pinamod $PINAMOD_DIR --delete
          
          echo "Syncing HF proxy content..."
          aws s3 sync s3://pinamod-artifacts-public/hf-proxy $HF_CONTENT_DIR --delete
          
          echo "Sync complete"
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_secret_access_key
        - name: PINAMOD_DIR
          value: /opt/models/pinamod
        - name: HF_CONTENT_DIR
          value: /opt/hf-content
        volumeMounts:
        - name: pina-models
          mountPath: /opt/models
        - name: hf-content
          mountPath: /opt/hf-content
      volumes:
      - name: pina-models
        hostPath:
          path: /opt/groundlight/edge/pinamod-public
          type: Directory
      - name: hf-content
        hostPath:
          path: /opt/groundlight/ee-mitm-proxy/content
          type: DirectoryOrCreate
  backoffLimit: 2