apiVersion: batch/v1
kind: Job
metadata:
  name: warmup-inference-model
spec:
  template:
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
      - name: registry-credentials
      containers:
      - name: image-puller
        image: 557423365154.dkr.ecr.us-west-2.amazonaws.com/gl-edge-inference:dev
        command: ["echo", "Successfully pulled image to warm cache"]
      - name: sync-pinamod
        image: amazon/aws-cli:latest
        # Sync models from S3 to the local hostmapped filesystem.
        command: ['sh', '-c', 'aws s3 sync s3://pinamod-artifacts-lkq/pinamod $PINAMOD_DIR --delete']
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_secret_access_key
        - name: PINAMOD_DIR
          value: /opt/models/pinamod
        volumeMounts:
        - name: pina-models
          mountPath: /opt/models
      volumes:
      - name: pina-models
        hostPath:
          path: /opt/groundlight/edge/pinamod-public
          type: Directory
  backoffLimit: 2