[project]
name = "memory-pressure-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "groundlight>=0.23.0",
    "opencv-python>=4.11.0.86",
]
