apiVersion: apps/v1
kind: Deployment
metadata:
  name: toxiproxy
  labels:
    app: toxiproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toxiproxy
  template:
    metadata:
      labels:
        app: toxiproxy
    spec:
      containers:
        - name: toxiproxy
          image: ghcr.io/shopify/toxiproxy:2.6.0
          imagePullPolicy: IfNotPresent
          args: ["-host=0.0.0.0", "-port=8474"]
          ports:
            - name: admin
              containerPort: 8474
            - name: listen
              containerPort: 443
          resources:
            requests:
              memory: "30Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: toxiproxy
  labels:
    app: toxiproxy
spec:
  selector:
    app: toxiproxy
  type: ClusterIP
  ports:
    - name: admin
      port: 8474
      targetPort: 8474
    - name: https
      port: 443
      targetPort: 443

