apiVersion: v1
kind: Service
metadata:
  name: {{ INFERENCE_SERVICE_NAME }}
spec:
  selector:
    app: inference-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ DEPLOYMENT_NAME }}
  labels:
    app: {{ DEPLOYMENT_NAME }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference-server
  template:
    metadata:
      labels:
        app: inference-server
    spec:
      # This service account is used by the edge-endpoint pod to access the Kubernetes API
      # from within the pod. See deploy/k3s/service_account.yaml for more details
      serviceAccountName: edge-endpoint-service-account
      containers:
      - name: inference-server
        image: 723181461334.dkr.ecr.us-west-2.amazonaws.com/gl-tritonserver:main-749c0cca3-dirty-0325a8beabe0d7b
        imagePullPolicy: IfNotPresent
        # Tritonserver will look for models in /mnt/models and initialize them on startup
        # TODO: We only want to shut down an old instance when this tritonsever gives the "READY" signal for all models
        command:
          ["tritonserver", "--model-repository=/mnt/models"]
        volumeMounts:
        - name: model-repo
          mountPath: /mnt/models
        - name: dshm
          mountPath: /dev/shm
        ports:
        - containerPort: 8000  # Default tritonserver HTTP port
      imagePullSecrets:
      - name: registry-credentials
      volumes:
      - name: model-repo
        hostPath:
          # A hostPath volume mounts a file or directory from the host node's filesystem into your Pod
          # This simiplifies things a lot, but only really works for single-node clusters.
          # TODO: check out k3s local path provisioner: https://docs.k3s.io/storage#setting-up-the-local-storage-provider
          path: /home/ubuntu/ptdev/zuuul2/predictors/serving/model_repository
          type: DirectoryOrCreate
      # https://stackoverflow.com/questions/43373463/how-to-increase-shm-size-of-a-kubernetes-container-shm-size-equivalent-of-doc
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 512Mi