apiVersion: v1
kind: Service
metadata:
  name: edge-endpoint
spec:
  selector:
    app: edge-endpoint
  ports:
  - protocol: TCP
    # Service port for NGINX 
    port: 6717 
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-endpoint
  labels:
    app: edge-endpoint
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: edge-endpoint
  template:
    metadata:
      labels:
        app: edge-endpoint
    spec:
      containers:
      - name: edge-endpoint 
        # Pull the image from ECR
        image: 723181461334.dkr.ecr.us-west-2.amazonaws.com/edge-endpoint:setup_k3s-f4ed4c6af-dirty-ffd5cf7460d9bf3
        imagePullPolicy: Always 
        ports:
        - containerPort: 6717 
        volumeMounts:
        - name: config-volume
          mountPath: /etc/configs/edge.yaml
        env: 
        - name: LOG_LEVEL
          value: "INFO"
        - name: GROUNDLIGHT_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: groundlight-secrets
              key: api-token 
      imagePullSecrets:
      - name: registry-credentials
      # We use a ConfigMap to store the edge.yaml file and mount it into the container
      # as a volume.
      volumes:
      - name: config-volume
        configMap:
          name: edge-config-yaml
