apiVersion: v1 
kind: PersistentVolume 
metadata:
  name: ${PERSISTENT_VOLUME_NAME}
spec:
  capacity: 
    storage: 2Gi
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: local-sc
  hostPath:
    path: /opt/groundlight/edge
---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: edge-endpoint-pvc
spec: 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-sc