
# To securely interact with the Kubernetes API from within a pod,
# Kubernetes uses a system called Role-Based Access Control (RBAC).
# When the Kubernetes Python client inside any pod tries to access
# the Kubernetes API, it needs to get auntheticated and authorized
# to access Kubernetes resources inside the cluster.
# Specifying a service account and a cluster role with full access
# to all resources in the cluster is the simplest way to do this.
# (i.e., any pod using the `edge-endpoint-service-account` will have
# full access to all resources in the cluster.)

# For more on RBAC, see:
# https://kubernetes.io/docs/reference/access-authn-authz/rbac/

apiVersion: v1
kind: ServiceAccount
metadata:
  name: edge-endpoint-service-account
  namespace: ${DEPLOYMENT_NAMESPACE}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ${DEPLOYMENT_NAMESPACE}
  name: limited-access-role
rules:
  # We only need to allow access to the resources that the edge logic needs
  # to access. In this case, we only need to allow access to pods and deployments.
  # The edge logic server will use the python kubernetes API to create deployments
  # and pods for the inference server.
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "get", "list", "watch", "delete", "update"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "get", "list", "watch", "delete", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edge-endpoint-role-binding
  namespace: ${DEPLOYMENT_NAMESPACE}
subjects:
- kind: ServiceAccount
  name: edge-endpoint-service-account
  namespace: ${DEPLOYMENT_NAMESPACE}
roleRef:
  kind: Role
  name: limited-access-role
  apiGroup: rbac.authorization.k8s.io