# Default values for groundlight-edge-endpoint.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: "edge"

imageTag: "latest"

edgeEndpointPort: 30101

persistentVolumeName: "edge-endpoint-pv"

inferenceFlavor: "gpu"

# The user must provide the Groundlight API token as input or the deployment will fail
groundlightApiToken: ""

# The user must provide the AWS Access Key Id as input or the deployment will fail
awsAccessKeyId: ""
# The user must provide the AWS Secret Access Key as input or the deployment will fail
awsSecretAccessKey: ""

# Currently, all Groundlight services are deployed in the us-west-2 region
awsRegion: "us-west-2"

ecrRegistry: "767397850842.dkr.ecr.us-west-2.amazonaws.com"

# These values override the automated settings in _helpers.tpl to keep this short and sweet
nameOverride: "edge-endpoint"
fullnameOverride: "edge-endpoint"