# Configure motion detection
motion_detection_templates:
  default:
    enabled: true
    val_threshold: 20
    percentage_threshold: 5.0
    # maximum time (seconds) between images sent to the cloud. This will be honored even if no
    # motion has been detected
    max_time_between_images: 3600
    # We cache the last image query from the cloud API. If the cached image query
    # still has low confidence after `unconfident_iq_reescalation_internal` seconds,
    # we will send a new image query to the cloud to try to get a higher confidence.
    unconfident_iq_reescalation_interval: 60

  super-sensitive:
    enabled: true
    val_threshold: 5
    percentage_threshold: 2.0
    max_time_between_images: 3600
    unconfident_iq_reescalation_interval: 60

  disabled:
    enabled: false

local_inference_templates:
  default:
    enabled: true
    # How often to fetch a new model binary (in seconds)
    refresh_rate: 120

  disabled:
    enabled: false

detectors:
  # Blank id implies that no detectors have been configured to use motion detection
  # and/or local edge inference. The "default" templates are just examples of how one
  # might configure these features.
    - detector_id: ''
      motion_detection_template: "default"
      local_inference_template: "default"
