local_inference_templates:
  default:
    enabled: true
    # How often to attempt to fetch a new ml model binary (in seconds)
    refresh_rate: 60

  disabled:
    enabled: false

detectors:
  # Blank id implies that no detectors have been configured to use local edge inference
  # The "default" templates are just examples of how one might configure inference.
    - detector_id: ''
      local_inference_template: "default"
      always_return_edge_prediction: false
      disable_cloud_escalation: false
