refresh_rate: 60 # How often to attempt to fetch updated ML models (in seconds). If not set, defaults to 60.

local_inference_templates:
  default:
    enabled: true

  disabled:
    enabled: false

detectors:
  # Blank id implies that no detectors have been configured to use local edge inference
  # The "default" templates are just examples of how one might configure inference.
    - detector_id: ''
      local_inference_template: "default"
      always_return_edge_prediction: false
      disable_cloud_escalation: false
      min_time_between_escalations: 2.0
