refresh_rate: 20 # How often to attempt to fetch a new ML model binary (in seconds). If not set, defaults to 60.

detectors:
  # Blank ID means that no detectors have been configured to use local edge inference.
    - detector_id: ''
      enabled: true
      local_inference_template: "default"
      always_return_edge_prediction: false
      disable_cloud_escalation: false
      min_time_between_escalations: 2.0