# Configure motion detection 
motion_detection_template:
  default:
    enabled: true
    val_threshold: 20
    percentage_threshold: 5.0
    # maximum time (seconds) between images sent to the cloud. This will be honored even if no
    # motion has been detected
    max_time_between_images: 3600

  super-sensitive:
    enabled: true
    val_threshold: 5
    percentage_threshold: 2.0
    max_time_between_images: 3600

  disabled:
    motion_detection_enabled: false

local_inference_template:
  default:
    enabled: true
    # The refresh rate in seconds for the local inference server 
    refresh_every: 3600

  super-fast-refresh:
    enabled: true
    refresh_every: 60

  disabled:
    enabled: false

detectors:
  - detector_id: ''
    motion_detection_template: "default"
    local_inference_template: "default"



