
# Configure motion detection parameters
motdet:
  - detector_id: 
    enabled: false
    percentage-threshold: 5.0
    val-threshold: 50
    # maximum time (seconds) between images sent to the cloud. This will be honored even if no
    # motion has been detected
    max-time-between-images: 3600
  
  - detector_id: 
    enabled: false
    percentage-threshold: 5.0
    val-threshold: 50
    # maximum time (seconds) between images sent to the cloud. This will be honored even if no
    # motion has been detected
    max-time-between-images: 3600
