
# Configure motion detection parameters
motion_detection:
  - detector_id: 'det_2U80DZ4lmJITkEJCfzlQOGu8SaS'
    motion_detection_enabled: false
    motion_detection_percentage_threshold: 5.0
    motion_detection_val_threshold: 50
    # maximum time (seconds) between images sent to the cloud. This will be honored even if no
    # motion has been detected
    motion_detection_max_time_between_images: 3600
  
  - detector_id: 'det_2U80DZ4lmJITkEJCfzlQOGu8SaSss'
    motion_detection_enabled: false
    motion_detection_percentage_threshold: 5.0
    motion_detection_val_threshold: 50
    # maximum time (seconds) between images sent to the cloud. This will be honored even if no
    # motion has been detected
    motion_detection_max_time_between_images: 3600
  
