
# Configure motion detection parameters
motion_detection:
  - detector_id: 
    enabled: false
    percentage_threshold: 5.0
    val_threshold: 50
    # maximum time (seconds) between images sent to the cloud. This will be honored even if no
    # motion has been detected
    max_time_between_images: 3600
  
  - detector_id: 
    enabled: false
    percentage_threshold: 5.0
    val_threshold: 50
    # maximum time (seconds) between images sent to the cloud. This will be honored even if no
    # motion has been detected
    max_time_between_images: 3600
