# For configuring detectors on the edge endpoint. See CONFIGURING-DETECTORS.md for more information.

global_config: # These settings affect the overall behavior of the edge endpoint.
  refresh_rate: 60 # How often to attempt to fetch updated ML models (in seconds). Defaults to 60.
  confident_audit_rate: 0.00001 # Probability that a confident prediction will be sent to cloud for auditing. Defaults to 1e-5 = a 0.001% chance.

edge_inference_configs: # These configs define detector-specific behavior and can be applied to detectors below.
  default: # Return the edge model's prediction if sufficiently confident; otherwise, escalate to the cloud.
    enabled: true
    always_return_edge_prediction: false
    disable_cloud_escalation: false
    min_time_between_escalations: 0

  edge_answers_with_escalation: # Always return the edge model's predictions, but still escalate to cloud if unconfident.
    enabled: true
    always_return_edge_prediction: true
    disable_cloud_escalation: false
    min_time_between_escalations: 0

  no_cloud: # Always return the edge model's prediction and never escalate to the cloud.
    enabled: true
    always_return_edge_prediction: true
    disable_cloud_escalation: true

  disabled: # Don't accept image queries on the edge endpoint for the associated detector.
    enabled: false

detectors: # Each entry here defines the edge configuration for a detector.
  # To configure a detector, add an entry for it below with its detector ID and the name of the edge inference config
  # you want to use. You can use or modify one of the existing edge inference configs listed above, or define your own.
    - detector_id: "det_2mIZTxUnJDhhUtJbUXavUevW15K" # edge_test_cat
      edge_inference_config: "default"
    - detector_id: "det_2yNfwyb7xPjXB1fSBXCmy9IwGqx"
      edge_inference_config: "edge_answers_with_escalation"
    - detector_id: "det_2yNfwEEn2dwAtgkv4ejhEj6LCQo"
      edge_inference_config: "no_cloud"
