# Configure motion detection 
motion_detection_templates:
  default:
    enabled: true
    val_threshold: 20
    percentage_threshold: 5.0
    # maximum time (seconds) between images sent to the cloud. This will be honored even if no
    # motion has been detected
    max_time_between_images: 3600

  super-sensitive:
    enabled: true
    val_threshold: 5
    percentage_threshold: 2.0
    max_time_between_images: 3600

  disabled:
    motion_detection_enabled: false

local_inference_templates:
  default:
    enabled: true
    # The refresh rate in seconds for the local inference server 
    refresh_every: 3600
    # Specifies the model name and model version to use for inference. 
    # If model_name is empty, the default model will be used.
    # For now we don't have a default model, so we need to specify a model name
    model_name: ''
    model_version: ''

  super-fast-refresh:
    enabled: true
    refresh_every: 60
    model_name: ''
    model_version: ''

  disabled:
    enabled: false

detectors:
  # Blank id indicates this is the default configuration.
  - detector_id: ''
    motion_detection_template: "default"
    local_inference_template: "default"



