# Auto assign random reviewers to Dependabot PRs
name: auto-assign

on:
  pull_request_target:
    types: [opened, ready_for_review, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  assign-pr-reviewer:
    # Only run this on Dependabot PRs
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: checkout code
      - name: randomly assign reviewer
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REVIEWERS=$(yq '.groups[0].usernames[]' .github/reviewer-lottery.yml)
          REVIEWER=$(echo "$REVIEWERS" | shuf -n 1)
          gh pr edit "${{ github.event.pull_request.number }}" --add-reviewer "$REVIEWER"
