name: build-push-ee-image
# This workflow is split into a separate file and called via workflow_call to enable triggering it
# from other repositories, to test new inference images. 
on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
      ref:
        required: true
        type: string
    secrets:
      AWS_GL_PUBLIC_ACCESS_KEY_ID:
        required: true
      AWS_GL_PUBLIC_SECRET_ACCESS_KEY:
        required: true
jobs:
  build-push-edge-endpoint-multiplatform:
    # This used to run on a larger runner, but to use it as a reusable workflow outside of this
    # orgnaization we need it to run on a default github runner. 
    # If we start seeing issues with the default runner again, there are some hacks to delete
    # unwanted software that's installed by default on the github runners to free up space. This is
    # already done in the test-k3s-helm workflow.
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_GL_PUBLIC_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_GL_PUBLIC_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: "true"
      - name: Check out code
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.ref }}
      - name: Build and Push Multiplatform edge-endpoint Image to ECR
        # This is actually only taking about 4 minutes right now.
        timeout-minutes: 45
        run: ./deploy/bin/build-push-edge-endpoint-image.sh