name: cicd
on: [push]

env: 
  PYTHON_VERSION: "3.11"
  POETRY_VERSION: "1.5.1"
  # This variable is used in the nginx.conf.template file
  PROXY_PASS_URL: https://app.groundlight.ai

jobs:
  # Run Groundlight SDK tests against the 
  # edge proxy endpoint set in nginx.conf file 
  test-sdk-via-proxy:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up python 
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Prepare NGINX proxy
        run: envsubst < nginx.conf.template > nginx.conf

      - name: Install Docker 
        run: | 
          sudo apt-get update
          sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install docker-ce
      - name: Build Docker Image 
        run: docker build --target production-image --tag groundlight-edge .

      - name: Start Docker container 
        run: docker run --rm -p 80:80 groundlight-edge

      - name: Install poetry 
        uses: snok/install-poetry@v1
        with: 
          version: ${{ env.POETRY_VERSION }}
          virtualenvs-create: true 
          virtualenvs-in-project: true 
          installer-parallel: true 

      # Note that we're pulling the latest main from the SDK repo
      # This might be ahead of what's published to pypi, but it's useful to test things before they're released.
      - name: Checkout Groundlight SDK 
        uses: actions/checkout@v3
        with:
          repository: groundlight/python-sdk
          path: groundlight-sdk
      - name: Install Groundlight SDK dependencies
        run: |
          cd groundlight-sdk 
          poetry install 

      - name: Run Groundlight SDK tests against Edge Proxy Endpoint
        env:
          # This is the token associated with the "edge-integ-user" (with shared credentials on 1password)
          GROUNDLIGHT_API_TOKEN: ${{ secrets.GROUNDLIGHT_API_TOKEN }}
          GROUNDLIGHT_ENDPOINT: http://localhost:8080/
        run: |
          cd groundlight-sdk 
          poetry run pytest 

  # Run unit tests 
  unit-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{hashFiles('**/poetry.lock') }}
      - name: Install package
        run: |
          poetry install --no-interaction --no-root
      - name: Run tests
        run: |
          poetry run pytest
