name: Update GLHub

on:
  pull_request:
    branches:
      - main

jobs:
  update-glhub:
    runs-on: ubuntu-latest
    environment: live

    steps:
      - name: Checkout glhub
        uses: actions/checkout@v4
        with:
          repository: groundlight/glhub
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          path: glhub

 
      - name: Update GLHub
        run: |
          cd glhub
          git config --global user.email "roxanne+gh_bot@groundlight.ai"
          git config --global user.name "edge-glhub-bot"
          git submodule update --init --recursive
          git submodule update --remote edge-endpoint
          git add .
          git commit -m "Update submodule"
          git push https://edge-glhub-bot:${{ secrets.BOT_GITHUB_TOKEN }}@github.com/groundlight/glhub.git main
        env:
          GIT_AUTHOR_NAME: "edge-glhub-bot"
          GIT_AUTHOR_EMAIL: "roxanne+gh_bot@groundlight.ai"
