name: Update GLHub

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout glhub
        uses: actions/checkout@v4
        with:
          repository: groundlight/glhub
          token: ${{ secrets.GH_PAT }}
          path: glhub

      - name: Update GLHub
        run: |
          cd glhub
          ls
