name: Update GLHub

on:
  push:

jobs:
  update-glhub:
    runs-on: ubuntu-latest
    environment: live

    steps:
      - name: Checkout glhub
        uses: actions/checkout@v4
        with:
          repository: groundlight/glhub
          token: ${{ secrets.GH_PAT }}
          path: glhub

      - name: Update GLHub
        run: |
          cd glhub
          git config --global user.email "roxanne@groundlight.ai"
          git config --global user.name "roxanne-o"
          git submodule update --init --recursive
          git submodule update --remote
          git add .
          git commit -m "Update submodule"
          git push https://roxanne-o:${{ secrets.GH_PAT }}@github.com/groundlight/glhub.git main
        env:
          GIT_AUTHOR_NAME: "roxanne-o"
          GIT_AUTHOR_EMAIL: "roxanne@groundlight.ai"
